### PR TITLE
Added enquiry formHandler - can be overridden by app

### PR DESCRIPTION
**Pull request by jeremyherr**
- Also added this as resultHandler to ContactForm

### CODE REVIEW

**Comment by lsbardel** [comment]
looks fine, can you add an entry in https://github.com/quantmind/lux/blob/master/release/nodes.md

**Comment by jeremyherr** [comment]
ok done

**Comment by lsbardel** [comment]
looks like tests are not passing

**Comment by jeremyherr** [comment]
The tests I added are failing on CI, but passing on my machine. So far I don't understand what the difference is.

The coverage going down is due to my adding a single optional parameter to a function call.

**Comment by jeremyherr** [comment]
Ah, thanks Reupen for noticing that the CI build is running tests against the bundle lux.js but it is not building the bundle itself. It expects the developer to commit the generated files to the repo.

**Pull request merged**
