### PR TITLE
Sidebar horizontal overflow

### PR DESCRIPTION
**Pull request by tazo90**
Ref: [https://github.com/quantmind/lux/issues/205](https://github.com/quantmind/lux/issues/205)
Tested on: Chrome, FF, Opera, IE9

**Preview**
sidebar-items

### CODE REVIEW

**Comment by jeremyherr** [comment]
The datasets look ok, but when you have multiple nesting, it's still messed up:

image

**Comment by tazo90** [comment]
thank you @jeremyherr, I will do neccessary fixes for multiple nesting.

**Comment by tazo90** [comment]
@jeremyherr I hope it will be fine now.

**Preview**
sidebar-items

**Comment by jeremyherr** [comment]
ok looks good

**Pull request merged**
