### PR TITLE
Fixes long user name in left panel menu

### PR DESCRIPTION
**Pull request by tazo90**
This fixes: [https://github.com/bmlltech/bmll-portal/issues/281](https://github.com/bmlltech/bmll-portal/issues/281)

### CODE REVIEW

**Comment by tazo90** [comment]
Below are results:

**long username**
long_username

**short username**
long_username_1

**Comment by lsbardel** [comment]
Any side effects?
In your snapshot looks like the username panel extend to the left!?

**Comment by tazo90** [comment]
No, I didn't saw any side effects.
There is a white bar on the left of the home item as it is active so it looks like that.

To make it obvious below are screenshots with a border:

**long username**
long_username

**short username**
short_username

**Comment by lsbardel** [comment]
thanks

**Pull request merged**
