### PR TITLE
Fix nav top border

### PR DESCRIPTION
**Pull request by tazo90**
This is fix for: [https://github.com/bmlltech/bmll-portal/issues/189](https://github.com/bmlltech/bmll-portal/issues/189)

### CODE REVIEW

**Comment by reupen** [comment]
This isn't quite the right fix; the problem still occurs if you make the navbar collapse, open the menu, then enlarge the window.

The standard Bootstrap navbar is hiding the border when the navbar isn't collapsed:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.css#L4245

Can we use a similar fix?

**Comment by tazo90** [comment]
Sure, I will check this.

**Comment by tazo90** [comment]
This issue is done.

**Comment by reupen** [comment]
@tazo90, this doesn't properly fix the problem as the line is there when the page first loads.

Also, there is similar code here but for some reason that page doesn't seem to be using the directive:
https://github.com/quantmind/lux/blob/master/luxjs/nav/nav.js#L152

Can we fix the CSS? We just need to hide the border for screen sizes above the collapse width.

**Comment by tazo90** [comment]
**@reupen**, the css fix won't work, because `bs-collapse` directive of `angular-strap` has bug and adds `.collapse.in` class event if menu isn't collapsed.

To solve it we need to remove `.in` class at first using `js`.

**Comment by reupen** [comment]
Yes, this works now. @lsbardel can we merge this?

**Pull request merged**
